### PR TITLE
Show dates on hover; Refactor out NUM_CASES_CUTOFF, Show cutoff on graph

### PR DESCRIPTION
**Pull request by prendradjaja**
Screen Shot 2020-03-30 at 6 44 18 PM
Screen Shot 2020-03-30 at 6 44 21 PM

### CODE REVIEW

**Comment by sollipse** [comment]
Have you tried this with "Alameda County?"
My worry is that this could get really long, since place names are unbounded. 

Ideally, a legend, and color-coded charts would solve this, I guess? So it might not be an issue. For now, to be safe, can we use a newline delimiter between the count and date, so that it takes up 2 lines, but less horizontal space?

**Comment by prendradjaja** [comment]
Screen Shot 2020-03-30 at 9 27 51 PM

**Comment by prendradjaja** [comment]
Seems like a nonissue for now! Also svg's `<text>` element doesn't support line breaks it looks like :(

**Comment by prendradjaja** [comment]
Rebased without changes

**Comment by prendradjaja** [comment]
Gonna go ahead and merge this -- feel free to (where you think it makes sense) do the same with future PRs too instead of waiting for me!

**Pull request merged**
